### Task 2 and 3 :--

Try to predict the semi finalist team and predict who is the of the semi final and after that we predict the winner of the final team and find that who is the winner of the final match.

Here we are using Sequantial NN model

Import all neccessary libreries.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dsPath = "/content/drive/MyDrive/DATASET/"

In [ ]:
matches = pd.read_csv(dsPath+'matches.csv')

In [ ]:
deliveries.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [ ]:
matches.head()

season         team1        team2        date  match_number  \
0  2023/24       England  New Zealand  2023/10/05             1   
1  2023/24      Pakistan  Netherlands  2023/10/06             2   
2  2023/24   Afghanistan   Bangladesh  2023/10/07             3   
3  2023/24  South Africa    Sri Lanka  2023/10/07             4   
4  2023/24     Australia        India  2023/10/08             5   

                                          venue        city  toss_winner  \
0                         Narendra Modi Stadium   Ahmedabad  New Zealand   
1            Rajiv Gandhi International Stadium   Hyderabad  Netherlands   
2  Himachal Pradesh Cricket Association Stadium  Dharamsala   Bangladesh   
3                          Arun Jaitley Stadium       Delhi    Sri Lanka   
4                        MA Chidambaram Stadium     Chennai    Australia   

  toss_decision     player_of_match          umpire1           umpire2  \
0         field          R Ravindra  HDPK Dharmasena       Nitin Menon   
1         field        Saud Shakeel     AT Holdstock          CM Brown   
2         field  Mehedi Hasan Miraz        JS Wilson   HDPK Dharmasena   
3         field          AK Markram   RK Illingworth      Sharfuddoula   
4           bat            KL Rahul      CB Gaffaney  RA Kettleborough   

  reserve_umpire  match_referee        winner  winner_runs  winner_wickets  \
0   Sharfuddoula      J Srinath   New Zealand          NaN             9.0   
1     PR Reiffel       JJ Crowe      Pakistan         81.0             NaN   
2      M Erasmus     AJ Pycroft    Bangladesh          NaN             6.0   
3       AG Wharf      J Srinath  South Africa        102.0             NaN   
4   AT Holdstock  RB Richardson         India          NaN             6.0   

  match_type  
0      Group  
1      Group  
2      Group  
3      Group  
4      Group

In [ ]:
matches.shape

(32, 18)

In [ ]:
matches["venue"].value_counts()

Himachal Pradesh Cricket Association Stadium                    5
MA Chidambaram Stadium                                          5
Arun Jaitley Stadium                                            4
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium    4
Rajiv Gandhi International Stadium                              3
Maharashtra Cricket Association Stadium                         3
Narendra Modi Stadium                                           2
M Chinnaswamy Stadium                                           2
Wankhede Stadium                                                2
Eden Gardens                                                    2
Name: venue, dtype: int64

In [ ]:
drop_columns = ["season","date","match_number","city","player_of_match","umpire1","umpire2","reserve_umpire","match_referee","match_type","winner_runs","winner_wickets"]

matches = matches.drop(columns=drop_columns)

In [ ]:
matches

team1         team2  \
0        England   New Zealand   
1       Pakistan   Netherlands   
2    Afghanistan    Bangladesh   
3   South Africa     Sri Lanka   
4      Australia         India   
5    New Zealand   Netherlands   
6        England    Bangladesh   
7      Sri Lanka      Pakistan   
8    Afghanistan         India   
9   South Africa     Australia   
10    Bangladesh   New Zealand   
11      Pakistan         India   
12   Afghanistan       England   
13     Sri Lanka     Australia   
14   Netherlands  South Africa   
15   New Zealand   Afghanistan   
16    Bangladesh         India   
17     Australia      Pakistan   
18   Netherlands     Sri Lanka   
19  South Africa       England   
20   New Zealand         India   
21      Pakistan   Afghanistan   
22  South Africa    Bangladesh   
23     Australia   Netherlands   
24       England     Sri Lanka   
25      Pakistan  South Africa   
26     Australia   New Zealand   
27   Netherlands    Bangladesh   
28         India       England   
29     Sri Lanka   Afghanistan   
30    Bangladesh      Pakistan   
31  South Africa   New Zealand   

                                                venue   toss_winner  \
0                               Narendra Modi Stadium   New Zealand   
1                  Rajiv Gandhi International Stadium   Netherlands   
2        Himachal Pradesh Cricket Association Stadium    Bangladesh   
3                                Arun Jaitley Stadium     Sri Lanka   
4                              MA Chidambaram Stadium     Australia   
5                  Rajiv Gandhi International Stadium   Netherlands   
6        Himachal Pradesh Cricket Association Stadium    Bangladesh   
7                  Rajiv Gandhi International Stadium     Sri Lanka   
8                                Arun Jaitley Stadium   Afghanistan   
9   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Australia   
10                             MA Chidambaram Stadium   New Zealand   
11                              Narendra Modi Stadium         India   
12                               Arun Jaitley Stadium       England   
13  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Sri Lanka   
14       Himachal Pradesh Cricket Association Stadium  South Africa   
15                             MA Chidambaram Stadium   Afghanistan   
16            Maharashtra Cricket Association Stadium    Bangladesh   
17                              M Chinnaswamy Stadium      Pakistan   
18  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   Netherlands   
19                                   Wankhede Stadium       England   
20       Himachal Pradesh Cricket Association Stadium         India   
21                             MA Chidambaram Stadium      Pakistan   
22                                   Wankhede Stadium  South Africa   
23                               Arun Jaitley Stadium     Australia   
24                              M Chinnaswamy Stadium       England   
25                             MA Chidambaram Stadium      Pakistan   
26       Himachal Pradesh Cricket Association Stadium   New Zealand   
27                                       Eden Gardens   Netherlands   
28  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       England   
29            Maharashtra Cricket Association Stadium   Afghanistan   
30                                       Eden Gardens    Bangladesh   
31            Maharashtra Cricket Association Stadium   New Zealand   

   toss_decision        winner  
0          field   New Zealand  
1          field      Pakistan  
2          field    Bangladesh  
3          field  South Africa  
4            bat         India  
5          field   New Zealand  
6          field       England  
7            bat      Pakistan  
8            bat         India  
9          field  South Africa  
10         field   New Zealand  
11         field         India  
12         field   Afghanistan  
13           bat     Australia  
14         field   Netherlands  
15         field

In [ ]:
matches.isnull().count()

team1            32
team2            32
venue            32
toss_winner      32
toss_decision    32
winner           32
dtype: int64

here check for winning_run and winning_wickets remove kari nne please!!!!!

In [ ]:
matches = matches.fillna(0)

In [ ]:
matches

team1         team2  \
0        England   New Zealand   
1       Pakistan   Netherlands   
2    Afghanistan    Bangladesh   
3   South Africa     Sri Lanka   
4      Australia         India   
5    New Zealand   Netherlands   
6        England    Bangladesh   
7      Sri Lanka      Pakistan   
8    Afghanistan         India   
9   South Africa     Australia   
10    Bangladesh   New Zealand   
11      Pakistan         India   
12   Afghanistan       England   
13     Sri Lanka     Australia   
14   Netherlands  South Africa   
15   New Zealand   Afghanistan   
16    Bangladesh         India   
17     Australia      Pakistan   
18   Netherlands     Sri Lanka   
19  South Africa       England   
20   New Zealand         India   
21      Pakistan   Afghanistan   
22  South Africa    Bangladesh   
23     Australia   Netherlands   
24       England     Sri Lanka   
25      Pakistan  South Africa   
26     Australia   New Zealand   
27   Netherlands    Bangladesh   
28         India       England   
29     Sri Lanka   Afghanistan   
30    Bangladesh      Pakistan   
31  South Africa   New Zealand   

                                                venue   toss_winner  \
0                               Narendra Modi Stadium   New Zealand   
1                  Rajiv Gandhi International Stadium   Netherlands   
2        Himachal Pradesh Cricket Association Stadium    Bangladesh   
3                                Arun Jaitley Stadium     Sri Lanka   
4                              MA Chidambaram Stadium     Australia   
5                  Rajiv Gandhi International Stadium   Netherlands   
6        Himachal Pradesh Cricket Association Stadium    Bangladesh   
7                  Rajiv Gandhi International Stadium     Sri Lanka   
8                                Arun Jaitley Stadium   Afghanistan   
9   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Australia   
10                             MA Chidambaram Stadium   New Zealand   
11                              Narendra Modi Stadium         India   
12                               Arun Jaitley Stadium       England   
13  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Sri Lanka   
14       Himachal Pradesh Cricket Association Stadium  South Africa   
15                             MA Chidambaram Stadium   Afghanistan   
16            Maharashtra Cricket Association Stadium    Bangladesh   
17                              M Chinnaswamy Stadium      Pakistan   
18  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   Netherlands   
19                                   Wankhede Stadium       England   
20       Himachal Pradesh Cricket Association Stadium         India   
21                             MA Chidambaram Stadium      Pakistan   
22                                   Wankhede Stadium  South Africa   
23                               Arun Jaitley Stadium     Australia   
24                              M Chinnaswamy Stadium       England   
25                             MA Chidambaram Stadium      Pakistan   
26       Himachal Pradesh Cricket Association Stadium   New Zealand   
27                                       Eden Gardens   Netherlands   
28  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       England   
29            Maharashtra Cricket Association Stadium   Afghanistan   
30                                       Eden Gardens    Bangladesh   
31            Maharashtra Cricket Association Stadium   New Zealand   

   toss_decision        winner  
0          field   New Zealand  
1          field      Pakistan  
2          field    Bangladesh  
3          field  South Africa  
4            bat         India  
5          field   New Zealand  
6          field       England  
7            bat      Pakistan  
8            bat         India  
9          field  South Africa  
10         field   New Zealand  
11         field         India  
12         field   Afghanistan  
13           bat     Australia  
14         field   Netherlands  
15         field

## Data transformations

Lable Encode the Venue and Toss Decision Columns

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

In [ ]:
matches["venue"] = label_encoder.fit_transform(matches["venue"])
matches["toss_decision"] = label_encoder.fit_transform(matches["toss_decision"])

In [ ]:
matches

team1         team2  venue   toss_winner  toss_decision  \
0        England   New Zealand      7   New Zealand              1   
1       Pakistan   Netherlands      8   Netherlands              1   
2    Afghanistan    Bangladesh      3    Bangladesh              1   
3   South Africa     Sri Lanka      0     Sri Lanka              1   
4      Australia         India      5     Australia              0   
5    New Zealand   Netherlands      8   Netherlands              1   
6        England    Bangladesh      3    Bangladesh              1   
7      Sri Lanka      Pakistan      8     Sri Lanka              0   
8    Afghanistan         India      0   Afghanistan              0   
9   South Africa     Australia      1     Australia              1   
10    Bangladesh   New Zealand      5   New Zealand              1   
11      Pakistan         India      7         India              1   
12   Afghanistan       England      0       England              1   
13     Sri Lanka     Australia      1     Sri Lanka              0   
14   Netherlands  South Africa      3  South Africa              1   
15   New Zealand   Afghanistan      5   Afghanistan              1   
16    Bangladesh         India      6    Bangladesh              0   
17     Australia      Pakistan      4      Pakistan              1   
18   Netherlands     Sri Lanka      1   Netherlands              0   
19  South Africa       England      9       England              1   
20   New Zealand         India      3         India              1   
21      Pakistan   Afghanistan      5      Pakistan              0   
22  South Africa    Bangladesh      9  South Africa              0   
23     Australia   Netherlands      0     Australia              0   
24       England     Sri Lanka      4       England              0   
25      Pakistan  South Africa      5      Pakistan              0   
26     Australia   New Zealand      3   New Zealand              1   
27   Netherlands    Bangladesh      2   Netherlands              0   
28         India       England      1       England              1   
29     Sri Lanka   Afghanistan      6   Afghanistan              1   
30    Bangladesh      Pakistan      2    Bangladesh              0   
31  South Africa   New Zealand      6   New Zealand              1   

          winner  
0    New Zealand  
1       Pakistan  
2     Bangladesh  
3   South Africa  
4          India  
5    New Zealand  
6        England  
7       Pakistan  
8          India  
9   South Africa  
10   New Zealand  
11         India  
12   Afghanistan  
13     Australia  
14   Netherlands  
15   New Zealand  
16         India  
17     Australia  
18     Sri Lanka  
19  South Africa  
20         India  
21   Afghanistan  
22  South Africa  
23     Australia  
24     Sri Lanka  
25  South Africa  
26     Australia  
27   Netherlands  
28         India  
29   Afghanistan  
30      Pakistan  
31  South Africa

Label Encode the Country which are teams between the matches are held.

In [ ]:
label_mapping = {'England' :0,'Pakistan':1,'South Africa' :2,'Australia':3,'New Zealand' :4,'Sri Lanka':5,'Bangladesh':6,'Netherlands':7,'India':8,'Afghanistan':9}

matches = matches.replace({"team1":label_mapping})
matches = matches.replace({"team2":label_mapping})
matches = matches.replace({"toss_winner":label_mapping})
matches = matches.replace({"winner":label_mapping})

In [ ]:
# matches = np.array(matches)

In [ ]:
matches


team1  team2  venue  toss_winner  toss_decision  winner
0       0      4      7            4              1       4
1       1      7      8            7              1       1
2       9      6      3            6              1       6
3       2      5      0            5              1       2
4       3      8      5            3              0       8
5       4      7      8            7              1       4
6       0      6      3            6              1       0
7       5      1      8            5              0       1
8       9      8      0            9              0       8
9       2      3      1            3              1       2
10      6      4      5            4              1       4
11      1      8      7            8              1       8
12      9      0      0            0              1       9
13      5      3      1            5              0       3
14      7      2      3            2              1       7
15      4      9      5            9              1       4
16      6      8      6            6              0       8
17      3      1      4            1              1       3
18      7      5      1            7              0       5
19      2      0      9            0              1       2
20      4      8      3            8              1       8
21      1      9      5            1              0       9
22      2      6      9            2              0       2
23      3      7      0            3              0       3
24      0      5      4            0              0       5
25      1      2      5            1              0       2
26      3      4      3            4              1       3
27      7      6      2            7              0       7
28      8      0      1            0              1       8
29      5      9      6            9              1       9
30      6      1      2            6              0       1
31      2      4      6            4              1       2

In [ ]:
type(matches["winner"])

pandas.core.series.Series

Define a function for winner team is team 1 or team 2.If the winner  == 1 then team 2 is winner otherwise team 1 is winner

In [ ]:
def winnerTeam(matches):
  winnerList = np.zeros(len(matches))
  for i in range(len(matches)):
    if(matches["winner"][i] == matches["team1"][i]):
      matches["winner"][i] = 0
    else:
      matches["winner"][i] = 1

winnerTeam(matches)

In [ ]:
matches

team1  team2  venue  toss_winner  toss_decision  winner
0       0      4      7            4              1       1
1       1      7      8            7              1       0
2       9      6      3            6              1       1
3       2      5      0            5              1       0
4       3      8      5            3              0       1
5       4      7      8            7              1       0
6       0      6      3            6              1       0
7       5      1      8            5              0       1
8       9      8      0            9              0       1
9       2      3      1            3              1       0
10      6      4      5            4              1       1
11      1      8      7            8              1       1
12      9      0      0            0              1       0
13      5      3      1            5              0       1
14      7      2      3            2              1       0
15      4      9      5            9              1       0
16      6      8      6            6              0       1
17      3      1      4            1              1       0
18      7      5      1            7              0       1
19      2      0      9            0              1       0
20      4      8      3            8              1       1
21      1      9      5            1              0       1
22      2      6      9            2              0       0
23      3      7      0            3              0       0
24      0      5      4            0              0       1
25      1      2      5            1              0       1
26      3      4      3            4              1       0
27      7      6      2            7              0       0
28      8      0      1            0              1       0
29      5      9      6            9              1       1
30      6      1      2            6              0       1
31      2      4      6            4              1       0

Split the Independent and Depedent Variables

In [ ]:
a  = [0,1,2,3,4]

X = matches.iloc[:,a].values
y = matches.iloc[:,5].values

X.shape,y.shape

((32, 5), (32,))

In [ ]:
y

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0])

## Building Nueral Network model Using Keras

import neccessaries libreries.

Here We use 2 dense layers with 64 nuerons in each layers and activation function as "RELU" and at output layer we use "softmax" as activation function.

In [ ]:
from keras.src.layers.serialization import activation
from keras.api._v2.keras.layers import Dense
from keras.src.engine.input_layer import Input
from tensorflow import keras
from keras.models import Sequential


inputs = Input(shape=(5,))

model = Sequential([
    keras.layers.InputLayer(input_shape=(5,)),
    keras.layers.Normalization(),
    keras.layers.Dense(64,activation="relu"),
    keras.layers.Dense(64,activation="relu"),
    keras.layers.Dense(1,activation = "softmax")
])


Compile the network use accuracy as matrix

In [ ]:
from keras.src.optimizers import RMSprop
model.compile(optimizer=RMSprop(learning_rate=0.001),loss="binary_crossentropy",metrics=["accuracy"])

fit the model on X

In [ ]:
model.fit(X,y,epochs=40,verbose=0)

for test we are predict match between the India VS Netherlad

In [ ]:
from numpy import array

X_test = array([[8,7,4,4,1]])
y_test = array([8])

In [ ]:
predict_x=model.predict(X_test)
classes_x=np.argmax(predict_x,axis=1)

1/1 [==============================] - 0s 71ms/step


In [ ]:
classes_x

array([0])

Here, We are predict the winner of the semifinalist team which is in between the India Vs New Zealand and provide the ground information where they can play.

Here we assume that toss winner is India and choose field first.

And our model try to predict and it will predict that India may win the semi finals.

In [ ]:
X_test = array([[8,4,3,8,0]])

In [ ]:
predict_x = model.predict(X_test)
classes_x = np.argmax(predict_x,axis=1)

1/1 [==============================] - 0s 23ms/step


In [ ]:
classes_x

array([0])

Here we are predict another Semi final match between Austrelia vs South Africa
and winner is South Africa

In [ ]:
X_test = array([[2,3,1,2,1]])

In [ ]:
predict_x = model.predict(X_test)

1/1 [==============================] - 0s 118ms/step


In [ ]:
classes_x = np.argmax(predict_x,axis=1)

In [ ]:
classes_x

array([0])

Here we will predict the final match between the India Vs South Africa. And indea win the toss and choose the bet first and Win the World Cup 2023

In [ ]:
X_test = array([[8,2,7,8,1]])

In [ ]:
predict_x = model.predict(X_test)

1/1 [==============================] - 0s 22ms/step


In [ ]:
classes_x = np.argmax(predict_x,axis=1)

In [ ]:
classes_x

array([0])